apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Values.projectName }}
  labels:
    apps: "{{ .Values.workerLocation }}-haproxy"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.haproxy.replicaCount }}
  selector:
    matchLabels:
      {{- include "haproxy-centos.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "haproxy-centos.selectorLabels" . | nindent 8 }}
      annotations:
      {{- if eq .Values.workerLocation "test" }}
        k8s.v1.cni.cncf.io/networks: {{- toYaml .Values.haproxy.multusIPs.test | indent 1 }}
      {{- else if eq .Values.workerLocation "pangyo" }}
        k8s.v1.cni.cncf.io/networks: {{- toYaml .Values.haproxy.multusIPs.pangyo | indent 1 }}
      {{- end }}
    spec:
      nodeSelector:
        location-node: "{{ .Values.workerLocation }}"
      {{- if eq .Values.workerLocation "test" }}
        {{- with .Values.haproxy.dnsSettings.dnsTest }}
          {{- toYaml . | nindent 6 }}
        {{- end }}
      {{- else if eq .Values.workerLocation "pangyo" }}
        {{- with .Values.haproxy.dnsSettings.dnsPg }}
          {{- toYaml . | nindent 6 }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.haproxy.securityContext | nindent 12 }}
          image: {{ template "haproxy-centos.deployer.image" . }}
          imagePullPolicy: {{ .Values.haproxy.image.pullPolicy | quote }}
          resources:
            {{- toYaml .Values.haproxy.resources | nindent 12 }}
          volumeMounts:
          {{- toYaml .Values.haproxy.volumeMounts | nindent 10 }}
      volumes:
      - name: v1
        configMap:
          name: {{ .Release.Name }}-config-configmap
      - name: v2
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-log-pvc
