{{- if .Values.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-log-pvc
  namespace: {{ .Values.projectName }}
  labels:
    apps: "{{ .Values.workerLocation }}-haproxy"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  selector:
    matchLabels:
      apps: "{{ .Values.workerLocation }}-haproxy"
{{- end }}
